### ISSUE TITLE
Lualine support

### ISSUE THREAD

**Issue by illegitimate-egg** [arturgoms/moonbow.nvim#1]
Lua line doesn't look to good with this theme, could you add support for it?
![image](https://user-images.githubusercontent.com/63966843/218341360-9dac8129-5c3a-42dc-ad55-0522c277ae2b.png)

**Comment by illegitimate-egg** [comment]
Also this theme shits itself if you reload your init.lua

**Comment by illegitimate-egg** [comment]
![image](https://user-images.githubusercontent.com/63966843/218453250-2c5a4968-5598-4c1c-ae42-ae3fcc06cd5e.png)

**Comment by arturgoms** [comment]
I'll keep the lualine issue support open but the other one is duplicated at #4

**Comment by illegitimate-egg** [comment]
Alright

**Comment by arturgoms** [comment]
Hey @illegitimate-egg, i just added a PR to lualine adding this theme to the list of supported themes. You can check here https://github.com/nvim-lualine/lualine.nvim/pull/966 when they merged. 

If you want to test before they merge you can use my fork of lualine that contains only the new theme as addiction. 
https://github.com/arturgoms/lualine.nvim

Remember that you need to add 
```lua
 options = { theme = "moonbow" } }
```
to the setup of lualine

**Comment by illegitimate-egg** [comment]
Awesome! thanks
