### ISSUE TITLE
Breaking changes in Treesitter markdown and markdown_inline

### ISSUE THREAD

**Issue by mBaratta96** [arturgoms/moonbow.nvim#14]
Hello,
love your colorscheme, but since the last update of Treesitter there is no highlight in Markdown files,

![Untitled](https://github.com/arturgoms/moonbow.nvim/assets/37810930/a7181238-f341-4f74-8f53-ff933450afce)

Looking at the issues, an update of your coloscheme may be required:

[Treesitter issue tracker](https://github.com/nvim-treesitter/nvim-treesitter/issues/2293#issuecomment-1900679583)

[List of changes](https://github.com/nvim-treesitter/nvim-treesitter/commit/1ae9b0e4558fe7868f8cda2db65239cfb14836d0)

I reverted to v0.9.2 at the moment, but I'd love to continue to use your colorschemes for the next releases. Thanks a lot

**Comment by arturgoms** [comment]
Glad you liked, thank you for the heads up, i'll make sure to update the theme!

**Comment by arturgoms** [comment]
close #15
