### ISSUE TITLE
Error when toggling colorscheme with preview in LazyVim

### ISSUE THREAD

**Issue by ukcw** [arturgoms/moonbow.nvim#2]
<img width="1303" alt="image" src="https://user-images.githubusercontent.com/34738958/218365631-02e7e3aa-c2bf-47a6-bbe2-9d3585a2e219.png">

Hi, I'm getting this Lua error when switching to moonbow using colorscheme with preview, whereas for other colorschemes, no errors are thrown. Has anyone ran into the same/similar error?

**Comment by number5** [comment]
I'm using `packer.nvim` with Neovim v0.9.0-dev-907+g2af31fc50-dirty,  got the same error when trying to switch to `moonbow`

**Comment by arturgoms** [comment]
Thank you for the issue. Can you check if the problem was solved in the latest commit?

**Comment by number5** [comment]
Can confirm,  532ed45 had fixed my issue.

Thank you very much for such a great colorscheme 😄

**Comment by ukcw** [comment]
Thanks for the fix and a great colorscheme Artur!
